// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef CubeViewUI_h
#define CubeViewUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Roller.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Group.H>
#include "CubeView.h"

class CubeViewUI {
public:
  CubeViewUI();
private:
  Fl_Double_Window *myWindow;
public:
  CubeView *cube;
  void show(int argc, char **argv);
};
#endif
