// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef EditorGui_h
#define EditorGui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Editor.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Menu_Bar.H>

class ConstrEditorUI {
public:
  ConstrEditorUI();
  Fl_Double_Window *fileWindow;
  Fl_Text_Editor *editor;
  Fl_Input *find;
  Fl_Menu_Bar *menuBar;
  static Fl_Menu_Item menu_menuBar[];
  Fl_Double_Window *outputWindow;
  Fl_Text_Editor *constrOutput;
  void show(int argc, char **argv);
};
#endif
