// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "EditorGui.h"

Fl_Menu_Item ConstrEditorUI::menu_menuBar[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Open", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Constraint", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Add", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Search", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Help", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

ConstrEditorUI::ConstrEditorUI() {
  { fileWindow = new Fl_Double_Window(740, 854);
    fileWindow->user_data((void*)(this));
    { editor = new Fl_Text_Editor(10, 60, 715, 775);
      editor->color(FL_FOREGROUND_COLOR);
      editor->textcolor((Fl_Color)55);
    } // Fl_Text_Editor* editor
    { find = new Fl_Input(355, 26, 290, 24);
    } // Fl_Input* find
    { new Fl_Button(655, 30, 63, 20, "Search");
    } // Fl_Button* o
    { menuBar = new Fl_Menu_Bar(0, 0, 740, 20, "menuBar");
      menuBar->menu(menu_menuBar);
    } // Fl_Menu_Bar* menuBar
    fileWindow->end();
    fileWindow->resizable(fileWindow);
  } // Fl_Double_Window* fileWindow
  { outputWindow = new Fl_Double_Window(539, 856);
    outputWindow->user_data((void*)(this));
    { constrOutput = new Fl_Text_Editor(5, 15, 525, 830, "Constraint Timing");
      Fl_Group::current()->resizable(constrOutput);
      constrOutput->window()->hotspot(constrOutput);
    } // Fl_Text_Editor* constrOutput
    outputWindow->end();
  } // Fl_Double_Window* outputWindow
}

void ConstrEditorUI::show(int argc, char **argv) {
  printf("Hello, World This is Broken!\n");
  fileWindow->show(argc, argv);
  outputWindow->show(argc, argv);
}
